# Generated by Django 3.2.12 on 2022-02-11 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0003_auto_20220211_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='guncellenme_tarihi',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kitap',
            name='yaratilma_tarihi',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
